# Generated by Django 4.2.1 on 2023-05-05 19:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_comment_options_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Launch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Имя запуска')),
                ('window_start', models.DateTimeField(verbose_name='Дата запуска')),
                ('window_end', models.DateTimeField(verbose_name='Дата окончания запуска')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.comment', verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Запуск',
                'verbose_name_plural': 'Запуски',
            },
        ),
    ]
