# Generated by Django 4.2.1 on 2023-05-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_launch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='launch',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='launch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.launch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='launch',
            name='name',
            field=models.CharField(max_length=600, verbose_name='Имя запуска'),
        ),
    ]
