# Generated by Django 4.2.1 on 2023-05-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_launch_comments_comment_launch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
