# Generated by Django 4.2.1 on 2023-05-20 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='launch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.launch'),
        ),
    ]
